<template>
  <div ref="table" />
</template>

<script>
import  "tabulator-tables/dist/css/tabulator_simple.min.css";

// Only for development
// import {TabulatorFull as Tabulator} from 'tabulator-tables';

import {
  Tabulator,
  FormatModule, MoveColumnsModule, SortModule
} from 'tabulator-tables';

Tabulator.registerModule([FormatModule, MoveColumnsModule, SortModule]);

export default {
  name: 'Tabulator',
  props: {
    data: {
      type: Array,
      required: true
    }
  },

  data () {
    return {
      tableInstance: undefined,
    }
  },

  watch: {
    // Update table data when provided data changes
    data () { this.updateData() }
  },

  mounted () {
    const columnsToAdd = [
      { title: "", field:"row_number", formatter:"rownum" }
    ]

    this.tableInstance = new Tabulator(this.$refs.table, {
      height: "100%",
      movableColumns: true,
      autoColumns: true,
      autoColumnsDefinitions: (definitions) => {

        // Change something on the autogenerated column definitions
        // definitions.forEach((column) => {
        //     column.headerFilter = true; // add header filter to every column
        // });

        // Add new, custom columns to the front
        columnsToAdd.forEach(newColumn => {
          definitions.unshift(newColumn)
        })

        return definitions;
      },
      // Data can be parsed directly here if no custom columns are used,
      // else there will be issues with the custom columns being
      // added to the data.
      data: JSON.parse(JSON.stringify(this.data))
    });
  },

  methods: {
    updateData () {
      if (!this.tableInstance) { return }

      this.tableInstance.setData(this.data)
    }
  }

}
</script>

<style lang="css">
/* Don't force complete width */
.tabulator {
  display: inline-block;
}

/* Onlzy show sort arrows on hover */
.tabulator-header .tabulator-col .tabulator-col-sorter {
  opacity: 0;
}
.tabulator-header .tabulator-col:hover .tabulator-col-sorter,
.tabulator-header .tabulator-col:active .tabulator-col-sorter,
.tabulator-header .tabulator-col:focus .tabulator-col-sorter {
  opacity: 1;
}

.tabulator-row.tabulator-selectable:hover {
  background-color: #eee;
}
</style>
